# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        DRUBU - Distribucion de rutas de buses
    #description:  symfony project
    #keywords:     symfony, project
    language:     es
    #robots:       index, follow
    viewport:     width=device-width,minimum-scale=1.0,maximum-scale=1.0

  stylesheets:    [common.css, yournavigation.css, small.css: { media: only screen and (max-width: 481px) }, large.css, print.css: { media: print }, main.css]

  javascripts:    [drubu.js, site.js, prototype.js]

  has_layout:     true
  layout:         layout
