<?php

/**
 * busTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class busTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object busTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('bus');
    }
}