<?php

/**
 * paradaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class paradaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object paradaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('parada');
    }
}