<?php

/**
 * rutaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class rutaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object rutaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ruta');
    }
}